site_name: "Data Delen Armoede en Schulden (DDAS): Vroegsignalering"
site_description: De uitwisselspecificatie voor de Data Delen over Armoede en Schulden (DDAS)
site_author: Arjen Brienen
site_dir: site/vroegsignalering
site_url: https://ddas-api.nl
repo_url: https://github.com/VNG-Realisatie/ddas
repo_name: GitHub
theme:
  language: nl # (1)!
  name: material
extra:
  version:
    provider: mike

nav:
  - Home: inleiding.md
  - Uitwisselspecificatie uitgelegd: uitleg_Model Vroegsignalering.md
  - Uitwisselspecificatie: uitwisselspecificatie.md
  - Informatiemodel:
    - Hoofdlijnen: "Hoofdlijnen_Model Vroegsignalering.md"
    - Detailspecificatie: "definities/Detail_Model Vroegsignalering.md"
  - Vraag en antwoord: VraagEnAntwoord.md
  - Achtergrond DDAS: Achtergrond.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.magiclink
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes

extra_css:
  - stylesheets/extra.css

plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: 'latest'
      version_selector: true
      css_dir: css
      javascript_dir: js

  - search